[package]
name = "zero-knowledge-journey"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.4"
cbc = "0.1.2"
cipher = "0.4.4"
hex = "0.4.3"
num-bigint = "0.4.6"
num-traits = "0.2.19"
serde = "1.0.228"
serde_json = "1.0.148"
sha1 = "0.10.6"

[[bin]]
name = "main"
path = "src/main.rs"
